# Generated by Django 3.2.9 on 2021-11-12 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umhapp_be', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='numero_documeto',
            new_name='numero_documento',
        ),
    ]
