# Generated by Django 3.2.9 on 2021-11-18 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umhapp_be', '0004_auto_20211116_2329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='numero_documeto',
            new_name='numero_documento',
        ),
    ]
