# Generated by Django 3.2.9 on 2021-11-19 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umhapp_be', '0006_rename_entity_doctor_institution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='institution',
            new_name='entity',
        ),
    ]
